INSERT INTO INVENTORY (INVENTORY_ID, LOCATION, LAST_UPDATED_DATE) VALUES (1, 'Warehouse A', '2024-12-01 10:30:00');
INSERT INTO INVENTORY (INVENTORY_ID, LOCATION, LAST_UPDATED_DATE) VALUES (2, 'Warehouse B', '2024-12-11 10:30:00');
INSERT INTO INVENTORY (INVENTORY_ID, LOCATION, LAST_UPDATED_DATE) VALUES (3, 'Warehouse C', '2024-12-21 10:30:00');
ALTER TABLE INVENTORY ALTER COLUMN INVENTORY_ID RESTART WITH (SELECT MAX(INVENTORY_ID) + 1 FROM INVENTORY);

INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (1, 'Laptop', 'High-performance laptop', 50, 1200.50, 'Electronics');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (2, 'Office Chair', 'Ergonomic office chair', 100, 85.99, 'Furniture');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (3, 'Desk Lamp', 'LED desk lamp', 200, 20.99, 'Lighting');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (4, 'Smartphone', 'Latest model smartphone', 30, 999.99, 'Electronics');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (5, 'Whiteboard', 'Magnetic whiteboard', 15, 45.75, 'Stationery');
ALTER TABLE ITEM ALTER COLUMN ITEM_ID RESTART WITH (SELECT MAX(ITEM_ID) + 1 FROM ITEM);

ALTER TABLE USERS RENAME TO "user";
INSERT INTO "user" (USER_ID, NAME, ADDRESS, ROLE, PHONE_NUMBER)
VALUES
    (1, 'Alice Johnson', '123 Elm Street, Cityville', 'SYSTEM ADMINISTRATOR', '+12345678901'),
    (2, 'Bob Smith', '456 Oak Avenue, Townsville', 'WAREHOUSE MANAGER', '+12345678902'),
    (3, 'Carol Davis', '789 Pine Road, Metropolis', 'SYSTEM_ADMINISTRATOR', '+12345678903'),
    (4, 'David Wilson', '321 Maple Drive, Suburbia', 'WAREHOUSE_STAFF', '+12345678904'),
    (5, 'Eve Brown', '654 Birch Lane, Urbania', 'WAREHOUSE_STAFF', '+12345678905');
ALTER TABLE "user" ALTER COLUMN USER_ID RESTART WITH (SELECT MAX(USER_ID) + 1 FROM "user");

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, STATUS, CREATED_DATE) VALUES (1, 1, 'PENDING', '2024-12-01 10:30:00');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, STATUS, CREATED_DATE) VALUES (2, 3, 'PROCESSING', '2024-12-02 15:45:00');
ALTER TABLE ORDERS ALTER COLUMN ORDER_ID RESTART WITH (SELECT MAX(ORDER_ID) + 1 FROM ORDERS);

INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 1, 2); -- Order 1: 2 Laptops
INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 3, 5); -- Order 1: 5 Notebooks
INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY) VALUES (2, 2, 4); -- Order 2: 4 Chairs


