INSERT INTO INVENTORY (INVENTORY_ID, LOCATION, LAST_UPDATED_DATE) VALUES (1, 'Warehouse A', '2024-12-01');
INSERT INTO INVENTORY (INVENTORY_ID, LOCATION, LAST_UPDATED_DATE) VALUES (2, 'Warehouse B', '2024-11-25');
INSERT INTO INVENTORY (INVENTORY_ID, LOCATION, LAST_UPDATED_DATE) VALUES (3, 'Warehouse C', '2024-11-15');

INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (1, 'Laptop', 'High-performance laptop', 50, 1200.50, 'Electronics');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (2, 'Office Chair', 'Ergonomic office chair', 100, 85.99, 'Furniture');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (3, 'Desk Lamp', 'LED desk lamp', 200, 20.99, 'Lighting');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (4, 'Smartphone', 'Latest model smartphone', 30, 999.99, 'Electronics');
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, QUANTITY, PRICE, CATEGORY) VALUES (5, 'Whiteboard', 'Magnetic whiteboard', 15, 45.75, 'Stationery');

INSERT INTO USERS (USER_ID, NAME, ADDRESS, ROLE) VALUES (1, 'Alice Johnson', '123 Elm Street, Cityville', 'Manager');
INSERT INTO USERS (USER_ID, NAME, ADDRESS, ROLE) VALUES (2, 'Bob Smith', '456 Oak Avenue, Townsville', 'Clerk');
INSERT INTO USERS (USER_ID, NAME, ADDRESS, ROLE) VALUES (3, 'Carol Davis', '789 Pine Road, Metropolis', 'Administrator');
INSERT INTO USERS (USER_ID, NAME, ADDRESS, ROLE) VALUES (4, 'David Wilson', '321 Maple Drive, Suburbia', 'Warehouse Staff');
INSERT INTO USERS (USER_ID, NAME, ADDRESS, ROLE) VALUES (5, 'Eve Brown', '654 Birch Lane, Urbania', 'Supervisor');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, STATUS, CREATED_DATE) VALUES (1, 1, 'PENDING', '2024-12-01 10:30:00');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, STATUS, CREATED_DATE) VALUES (2, 3, 'PROCESSING', '2024-12-02 15:45:00');

INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 1, 2); -- Order 1: 2 Laptops
INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 3, 5); -- Order 1: 5 Notebooks
INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY) VALUES (2, 2, 4); -- Order 2: 4 Chairs


